title: explore-project-template
hero_image: images/banner.png
description: explore-project-template description
version: 4
listed: false
copyedit: false
last_tested: "2021-03-26"
steps:
  - title: Introduction
  - title: Gather your images
  - title: Retrain a model with Teachable Machine
  - title: Retrain a model with a script
  - title: Testing your new model
