title: Image classification with Google Coral
hero_image: images/banner.png
description: Learn how to retrain a machine learning model and use it for image identification.
version: 4
listed: false
copyedit: false
last_tested: "2021-03-26"
steps:
  - title: Introduction
  - title: Gather your images
  - title: Retrain a model online, with Teachable Machine
  - title: Retrain a model on your Raspberry Pi
  - title: Testing your new model
  - title: Mission Space Lab
