---
title: Image classification with Google Coral
hero_image: images/banner.png
description: Learn how to retrain a machine learning model and use it for image identification.
version: 4
listed: true
copyedit: true
last_tested: '2021-03-26'
steps:
- title: Introduction
  completion: engaged
- title: Set up your Coral and gather your images
- title: Retrain a model online, with Teachable Machine
- title: Retrain a model on your Raspberry Pi
- title: Testing your new model
  completion: internal
- title: Mission Space Lab
